metadata:
  name: kfp-with-mlrun-image-kfp-xingsheng
  created: '2025-07-03T16:46:23.565000'
spec:
  default_image: .mlrun-project-image-kfp-with-mlrun-image-kfp
  desired_state: online
  workflows:
  - name: dummy
    image: .mlrun-project-image-kfp-with-mlrun-image-kfp
    path: ./src/workflows/dummy.py
  source: git://github.com/xsqian/slim-call-center.git#main
  owner: xingsheng
  conda: ''
  params:
    build_image: false
    source: git://github.com/xsqian/slim-call-center.git#main
    default_image_name: .mlrun-project-image-kfp-with-mlrun-image-kfp
  load_source_on_run: true
  build:
    image: .mlrun-project-image-kfp-with-mlrun-image-kfp
    commands:
    - apt-get update -y && apt-get install ffmpeg -y
    - pip install transformers==4.44.1
    - pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu
    - pip install mlrun langchain==0.2.17 openai==1.58.1 langchain_community==0.2.19
      pydub==0.25.1 streamlit==1.28.0 st-annotated-text==4.0.1 spacy==3.7.2 librosa==0.10.1
      presidio-anonymizer==2.2.34 presidio-analyzer==2.2.34 nltk==3.8.1 flair==0.13.0
      htbuilder==0.6.2
    - python -m spacy download en_core_web_lg
    - pip install SQLAlchemy==2.0.31
    - pip uninstall -y onnxruntime-gpu onnxruntime
    - pip install onnxruntime
    - pip show sqlalchemy
    - python --version
    base_image: mlrun/mlrun-kfp
  functions:
  - url: ./src/printdummy.py
    name: printdummy
    kind: job
    handler: print_dummy
  - url: ./src/printdummy.py
    name: dummy
    kind: job
    with_repo: true
  - url: ./src/sub/printdummy.py
    name: another-dummy
    kind: job
    with_repo: true
  origin_url: git://github.com/xsqian/slim-call-center.git#refs/heads/main
kind: project
status:
  state: online
