spec:
  build:
    image: .mlrun-project-image-kfp-with-mlrun-image-kfp
    commands:
    - echo "BEFORE BEFORE get the image and print out the python version"
    - python --version
    - pip install SQLAlchemy==2.0.31
    - pip show sqlalchemy
    - pip show requests_toolbelt
    - echo "AFTER AFTER an installation and print out the python version"
    - python --version
    base_image: mlrun/mlrun-kfp
  owner: xingsheng
  conda: ''
  params:
    build_image: true
    source: git://github.com/xsqian/slim-call-center.git#main
    default_image_name: .mlrun-project-image-kfp-with-mlrun-image-kfp
    default_image: .mlrun-project-image-kfp-with-mlrun-image-kfp
  functions:
  - url: ./src/printdummy.py
    name: printdummy
    kind: job
    handler: print_dummy
  - url: ./src/printdummy.py
    name: dummy
    kind: job
    with_repo: true
  - url: ./src/sub/printdummy.py
    name: another-dummy
    kind: job
    with_repo: true
  - url: hub://text_to_audio_generator
    name: text-to-audio-generator
    kind: job
  default_image: .mlrun-project-image-kfp-with-mlrun-image-kfp
  origin_url: git://github.com/xsqian/slim-call-center.git#refs/heads/main
  load_source_on_run: true
  workflows:
  - image: .mlrun-project-image-kfp-with-mlrun-image-kfp
    path: ./src/workflows/dummy.py
    name: dummy
  source: git://github.com/xsqian/slim-call-center.git#main
  desired_state: online
kind: project
status:
  state: online
metadata:
  name: kfp-with-mlrun-image-kfp-xingsheng
  created: '2025-07-03T16:46:23.565000'
