status:
  state: online
spec:
  build:
    commands:
    - pip install SQLAlchemy==2.0.31 &&               echo "" > /empty/requirements.txt
      &&               ls -l /empty/ &&               cat /empty/Dockerfile &&               ls
      -l /home/ &&               rm -rf /home/mlrun-code/project_setup.py
    image: .slim-demo-call-center-kfp
    base_image: mlrun/mlrun-kfp
    source_code_target_dir: /home/mlrun_code/
  load_source_on_run: false
  workflows:
  - path: ./src/workflows/dummy.py
    name: dummy
    image: .slim-demo-call-center-kfp
  default_image: .mlrun-project-image-kfp-with-mlrun-image-kfp
  desired_state: online
  params:
    build_image: false
    source: git://github.com/xsqian/slim-call-center.git#dan
    default_image_name: .mlrun-project-image-kfp-with-mlrun-image-kfp
    default_image: .mlrun-project-image-kfp-with-mlrun-image-kfp
  source: git://github.com/xsqian/slim-call-center.git#dan
  origin_url: git://github.com/xsqian/slim-call-center.git#refs/heads/dan
  owner: xingsheng
  conda: ''
  functions:
  - url: ./src/printdummy.py
    name: printdummy
    kind: job
    handler: print_dummy
  - url: ./src/printdummy.py
    name: dummy
    kind: job
    with_repo: true
  - url: ./src/sub/printdummy.py
    name: another-dummy
    kind: job
    with_repo: true
  - url: hub://text_to_audio_generator
    name: text-to-audio-generator
    kind: job
metadata:
  name: kfp-with-mlrun-image-kfp-xingsheng
  created: '2025-07-03T16:46:23.565000'
kind: project
