status:
  state: online
spec:
  load_source_on_run: false
  source: git://github.com/xsqian/slim-call-center.git#dan
  default_image: .mlrun-project-image-kfp-with-mlrun-image-kfp
  functions:
  - url: ./src/printdummy.py
    name: printdummy
    kind: job
    handler: print_dummy
  - url: ./src/printdummy.py
    name: dummy
    kind: job
    with_repo: true
  - url: ./src/sub/printdummy.py
    name: another-dummy
    kind: job
    with_repo: true
  - url: hub://text_to_audio_generator
    name: text-to-audio-generator
    kind: job
  desired_state: online
  owner: xingsheng
  origin_url: git://github.com/xsqian/slim-call-center.git#refs/heads/main
  workflows:
  - path: ./src/workflows/dummy.py
    image: .mlrun-project-image-kfp-with-mlrun-image-kfp
    name: dummy
  conda: ''
  params:
    build_image: true
    source: git://github.com/xsqian/slim-call-center.git#dan
    default_image_name: .mlrun-project-image-kfp-with-mlrun-image-kfp
    default_image: .mlrun-project-image-kfp-with-mlrun-image-kfp
  build:
    base_image: mlrun/mlrun-kfp
    image: .mlrun-project-image-kfp-with-mlrun-image-kfp
    commands:
    - apt-get update -y && apt-get install ffmpeg -y
    - echo 'mlrun-kfp'
    - python --version
    - pip install transformers==4.44.1
    - pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu
    - python --version
    - pip install bitsandbytes==0.41.1 accelerate==0.24.1 datasets==2.14.6 peft==0.5.0
      optimum==1.13.2
    - python --version
    - pip install mlrun langchain==0.2.17 openai==1.58.1 langchain_community==0.2.19
      pydub==0.25.1 streamlit==1.28.0 st-annotated-text==4.0.1 spacy==3.7.2 librosa==0.10.1
      presidio-anonymizer==2.2.34 presidio-analyzer==2.2.34 nltk==3.8.1 flair==0.13.0
      htbuilder==0.6.2
    - python -m spacy download en_core_web_lg
    - pip install SQLAlchemy==2.0.31
    - pip uninstall -y onnxruntime-gpu onnxruntime
    - pip install onnxruntime
    - pip install requests_toolbelt==0.10.1
    - pip show sqlalchemy
    - pip show requests_toolbelt
    - python --version
    source_code_target_dir: /home/mlrun_code/
metadata:
  name: kfp-with-mlrun-image-kfp-xingsheng
  created: '2025-07-03T16:46:23.565000'
kind: project
